apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "necesse-server.fullname" . }}
  labels:
    {{- include "necesse-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "necesse-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "necesse-server.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if or .Values.image.pullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      {{- end }}
      containers:
        - name: necesse-server
          image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}{{ else }}{{ .Values.image.registry }}{{ end }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          {{- end }}
          env:
            - name: WORLD
              value: {{ .Values.necesse.world | quote }}
            - name: PASSWORD
              value: {{ .Values.necesse.password | quote }}
            - name: SLOTS
              value: {{ printf "%d" .Values.necesse.slots | quote }}
            - name: OWNER
              value: {{ .Values.necesse.owner | quote }}
            - name: MOTD
              value: {{ .Values.necesse.motd | quote }}
            - name: GIVE_CLIENTS_POWER
              value: {{ printf "%d" .Values.necesse.giveClientsPower | quote }}
            - name: PAUSE
              value: {{ printf "%d" .Values.necesse.pause | quote }}
            - name: LOGGING
              value: {{ printf "%d" .Values.necesse.logging | quote }}
            - name: ZIP
              value: {{ printf "%d" .Values.necesse.zip | quote }}
            - name: JVMARGS
              value: {{ .Values.necesse.jvmArgs | quote }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- if .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml .Values.extraEnvFrom | nindent 12 }}
          {{- end }}
          ports:
            - name: game
              containerPort: {{ .Values.containerPorts.game }}
              protocol: UDP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: necesse-data
              mountPath: /necesse
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: necesse-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{- if .Values.persistence.existingClaim }} {{ .Values.persistence.existingClaim }} {{- else }} {{ include "necesse-server.fullname" . }} {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

